### ISSUE TITLE
Remove stylewikipedia from style options

### ISSUE THREAD

**Issue by quiddity-wp** [pmsf/PMSF#304]
The map tiles from Wikipedia are not currently available to external sites. ([per](https://phabricator.wikimedia.org/T245145#5880898))
Software like this, overloaded it. :-/
Please remove it from the options, as it is not likely to come back. 
Thank you!

**Comment by whitewillem** [comment]
fixed in https://github.com/pmsf/PMSF/commit/5a2ae89db61a806a46ba6ac971637c4134f510f7
