### ISSUE TITLE
New users are not registering in database.

### ISSUE THREAD

**Issue by klablabla** [pmsf/PMSF#374]
**Describe the bug**
When you have used the database and deleted some users. It won't create new users.

**To Reproduce**
Create a few users.
Delete one user
error

**Expected behavior**
Let the auto increment on id do it's work in the user table.

**Additional context**
If we get rid of the $getid. Or if getid looks at the highest id instead of calculating. It is fixed.

**Comment by jepke** [comment]
This is all going to change. In the upcoming release the id column will no longer be auto increment.
