### ISSUE TITLE
add gen 6 support for tomorrow's event

### ISSUE THREAD

**Issue by Soda-City-PoGo** [pmsf/PMSF#406]
**Is your feature request related to a problem? Please describe.**
`currently only shows up to gen 5 pokemon`
**Describe the solution you'd like**
`add a section in config.php to allow for user to edit max pokemon number`
**Describe alternatives you've considered**

**Additional context**

**Comment by thermoscookies** [comment]
You can add `$numberOfPokemon = 721;` to your config.

**Comment by Soda-City-PoGo** [comment]
thats a band-aid tho

**Comment by thermoscookies** [comment]
It's exactly what you asked for. It's always existed just wasn't in config.php because it isn't something that needs to be changed very often. Any of the variables from default.php can be placed into config.php, but default.php should not be edited itself.

**Comment by Pogodenhelder** [comment]
i added $numberOfPokemon = 721; in some custom made part of the config ( just in case i think ow its custom lol ) and works.

**Comment by DavisPoGo** [comment]
I added $numberOfPokemon = 721 to config.php. In the Raid Filtering menu, the Espurr icon is missing. Additionally, the change to config.php breaks the reward search function (using the magnifying glass)

**Comment by whitewillem** [comment]
fixed with pr407. You can always overwrite default.php with config.php so up to you if you want to add it to config.php
