### ISSUE TITLE
Users prematurely logged out

### ISSUE THREAD

**Issue by Gladiator10864** [pmsf/PMSF#440]
**Describe the bug**
iOS and MacOS users frequently receive the error message saying they have been logged out when switching between apps. Hitting the back button brings them back to normal and still logged in.

**To Reproduce**
Using iOS device:
1. Log into map with Discord
2. Switch to another app and use for a few minutes
3. Switch back to map and you will get the "You have been logged out" window (seems to happen randomly but frequently)

**Expected behavior**
Map should load as normal with saved settings.

**Desktop (please complete the following information):**
 - OS: iOS, MacOS
 - Browser Chrome, Safari, Firefox
 - Version ?

**Smartphone (please complete the following information):**
 - Device: iPad early 2018 and various unknown reports from users
 - OS: iOS 14.3 and various unknown reports from users
 - Browser Chrome, Safari and various unknown reports

**Comment by jepke** [comment]
I know this has/was/is an issue but few attempts have been made to solve it. Tried replicating but unsuccessful. Please let me know if this is still ongoing.

**Comment by plinytheelder** [comment]
Most of us had this issue. Eventually we figured out to adjust session timeout in the php.ini file itself

https://stackoverflow.com/questions/9904105/php-sessions-default-timeout

**Comment by jepke** [comment]
@plinytheelder that should not be necessary but can most likely make the issue less annoying.

Still planning on 2nd partial rewrite of the login stuff as part of a bigger thing

**Comment by jepke** [comment]
Another complete overhaul of auth planned
