### ISSUE TITLE
Redundant form handling for icons

### ISSUE THREAD

**Issue by Boby360** [pmsf/PMSF#445]
On occasion, for whatever reason the map starts looking for a new form ID for a pokemon.
The sidebar shows the icons and does not use any form ID so 195_00.png
The map requests for the form ID. 195_1229.png

While we would ideally like to see these pokemon in the right form, for whatever reason random form IDs (Im guessing) have been requested. So we end up with a request to 195_1229.png despite the form not existing. This means we have to make constant duplicates of icons for normal operation.

Can we adjust the code to look for 195_00.png IF the requested form is missing?

**Comment by nileplumb** [comment]
this is actually being worked on with a new icon format update between different projects https://discord.gg/cG8JwrJB6Z
