### ISSUE TITLE
Feature Request: Toggle for map to use alternate datasource for A/B quest data

### ISSUE THREAD

**Issue by kbtbc** [pmsf/PMSF#525]
Now that RDM supports scanning the two different quest types `normal` and `ar`, it would be great if we could get PMSF to add a user-toggle to be able to switch datasources from the map.   A simple 'AR Quests Only' button in Pokestop options would work. 

![image](https://user-images.githubusercontent.com/7109934/129412292-47267268-d8f7-4e1f-ac17-5f07112ba778.png)
Sample of side-by-side normal and ar type scan.   Hoping to be able to toggle between these views :)

**Comment by TiMXL73** [comment]
closing. already implemented.
